### ISSUE TITLE
Missing directories

### ISSUE THREAD

**Issue by Joseph-Moretto** [QinbinLi/LLM-PBE#1]
Sorry if I am just missing them, but it appears that some of directories mentioned in the various readme's are not in the publicly accessible branch

For example, I was interested in some of the defense methods and was looking for some things in that directory. 
The readme references a "prompts" directory that is not present. I noticed that the prompts directory was also missing in the attacks folder, but was referenced in the readme.

**Comment by QinbinLi** [comment]
Hi @Joseph-Moretto ,

Sorry for the confusion. We have updated README to make it consistent with the directories. If you are looking for the defense prompts, they are available in https://github.com/QinbinLi/LLM-PBE/blob/main/attacks/PromptLeakage/prompt_leakage.py (lines 58-68).
