### ISSUE TITLE
About other LLM like LLama series finetune?

### ISSUE THREAD

**Issue by Zuo-Lihan** [QinbinLi/LLM-PBE#3]
Hello, QinbinLi,
I'm from SUTD. It's ok with GPT2 series finetuning, but when the architecture comes to LLama series, it will report  a ValueError.

The picture is from 'pii_leakage' site-package:
![image](https://github.com/user-attachments/assets/4b8e53c4-f68b-4495-a7e7-558388545632)

Can you teach me how to solve it? I want to fine-tune on other LLMs like LLama series.

**Comment by jyhong836** [comment]
Hi. The pii_leakage does not support models newer than gpt2. We will release a new version of code soon.

**Comment by Zuo-Lihan** [comment]
I see. I appreciate very much for your work. I'm looking forward to see the new version of this codebase available soon.

**Comment by jyhong836** [comment]
Here you go! 
https://github.com/jyhong836/llm-dp-finetune

**Comment by Zuo-Lihan** [comment]
So many thanks!
