### ISSUE TITLE
repository clone failed on Windows

### ISSUE THREAD

**Issue by jestyf** [QinbinLi/LLM-PBE#4]
when I clone this repo on a Windows computer, I get this error:
![image](https://github.com/user-attachments/assets/c97c8d7a-f0f4-49ac-997d-841d381543b6)
In the Windows operating system, a file or a folder named with the character `:` is not supported. sadly in your repo, there are some folders whose name has `:`.
![image](https://github.com/user-attachments/assets/c52d96ef-0d5c-4b01-9d63-754559cbf75a)
I just cloned this repo on another Linux computer, but could you change its name for those folders, so that other developers can clone this repo on Windows?

**Comment by QinbinLi** [comment]
Hi @jestyf ,

Thank you! We have fixed the naming issue.
