### ISSUE TITLE
For the Data_Extraction Attack

### ISSUE THREAD

**Issue by Zuo-Lihan** [QinbinLi/LLM-PBE#5]
After run 'python -m attacks.DataExtraction.extract_enron_local --model EleutherAI/pythia-14m --arch EleutherAI/pythia-14m --peft none', 

the extraction will obtain a generation_file but I do not see a metric.py to evaluate the generation. 
May I ask for your help with offering the evaluations of 'attacks.DataExtraction'?

**Comment by QinbinLi** [comment]
Hi @Zuo-Lihan ,

You can refer to `https://github.com/QinbinLi/LLM-PBE/blob/main/notebooks/metric_data_extraction.ipynb`. You may change `read_all_models` function to load your generated files.
