### ISSUE TITLE
could not find fine-tuned models on Huggingface

### ISSUE THREAD

**Issue by richardsun-voyager** [QinbinLi/LLM-PBE#6]
I tried to download the fine-tuned weights from Huggingface: https://huggingface.co/LLM-PBE/enron-llama2-7b-undefended but only saw "404". Can you upload the fine-tuned weights? Thanks!

**Comment by QinbinLi** [comment]
Hi @richardsun-voyager ,

We have updated the model list in Huggingface `https://huggingface.co/LLM-PBE` and changed the visibility of the models. Please refer to the new list.
